services:
  nextjs-service:
    ports:
      - 3200:3000
    build:
      context: ./
      dockerfile: Dockerfile

  mysql:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root@mysql
      - MYSQL_USER=twitch
      - MYSQL_PASSWORD=twitch@root
      - MYSQL_DATABASE=twitch

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040

